---
- hosts: nagios-servers
  remote_user: "{{ ansible_system_user }}"
  tasks: []

# role for nagios clients via NRPE
- hosts: nagios-servers
  roles:
    
    - { role: ansible/nagios-client }
    - { role: ansible/firewall_client, when: manage_firewall_client }

# role for nagios server
- hosts: nagios-servers
  remote_user: "{{ ansible_system_user }}"
  roles:
    - { role: ansible/nagios }
    - { role: ansible/firewall, when: manage_firewall }
    - { role: ansible/instructions }
